const userInput = document.getElementById('user-input');
const responseContainer = document.getElementById('response-container');
const chatLog = document.getElementById('chat-log');
const submitButton = document.getElementById('submit-button');


submitButton.addEventListener('click', handleUserInput);

userInput.addEventListener('keypress', (e) => {
  if (e.key === 'Enter') {
    handleUserInput();
  }
});

function handleUserInput() {
  const userQuestion = userInput.value.trim();
  if (userQuestion) {
    const response = generateResponse(userQuestion);
    displayResponse(response);
    userInput.value = ''; // Clear the input field
    //savechat
  }
}

function generateResponse(userQuestion) {
 
  
    switch (userQuestion) {
      case 'Hi':
      case 'hi':
        return 'Hi, I am an AI. Generated by AyyanAli.'; 
      case 'AssalamoAlaikum':
      case 'assalamoalaikum':
        return 'WalaikumAslam. How can I assist you?';
      case 'Who is ayyan':
      case 'who is ayyan':
          case 'tell me about ayyan':
        return 'Ayyan is a Frontend Developer.';
      case 'give me information about ayyan':
      case 'please tell me about ayyan':
        return 'Ayyan is a Frontend Developer. He is 13 years old. He is a student of class 9.';
      case 'Who can made you':
      case 'who can generate you':
        return 'I am generated and made by Ayyan.';
      case 'Hello':
      case 'hello':
        return 'Hi, I am AI. Generated by Ayyan.';
      case 'What is your purpose':
      case 'what is your purpose':
          case "why you can made":
        return 'I am here to assist you with any questions or tasks you may have.';
      case 'Can you write a poem':
      case 'can you write a poem':
          case "write a poem":
        return 'Not until,But, in future I can write a poems and many other things.';
      case 'Can you tell me a joke':
      case 'can you tell me a joke':
        return 'Yes, I can tell you a joke. Here is one: Why did the computer go to the doctor? It had a virus!';
        case 'Who are you?':
          case 'who are you':
            return 'I am a AI Assistant.How can i assist you';
            case 'how are you':
          case 'How are you':
            return 'I am Fine.How are You?';
            case 'I am fine?':
          case 'i am fine':
            case "i am also fine":
            return 'OO,Thats`Good';
            case 'Can you tell me a joke':
              case'tell me a joke':
                return 'Yes, I can tell you a joke. Here is one:What do you call a fake noodle?An impasta!';
                case 'Another joke that make me Laugh.':
                  case 'another joke':
                      case'another':
                    return 'Yes, I can tell you another joke. Why did the scarecrow win an award?Because he was outstanding in his field';
                    case 'How many language do you know':
                       case 'how many language do you know':
                          case 'how many languages you know':
                        return 'I will know English.But,In future, I will be available in many languages.';
                        case 'Who are you':
                          case 'who is ai':
                       case 'tell me about you':
                        return 'AI (Artificial Intelligence) refers to intelligence exhibited by machines, particularly computer systems ¹. AI research aims to develop and study methods and software that enable machines to perceive their environment and use learning and intelligence to take actions that maximize their chances of achieving defined goals .'
                        case 'Who can built you?':
                       case 'who can built you':
                          case 'who can made you':
  
                          case'who owns you':
                        return 'I will be built by Ayyan Ali.';
  
  
                        case 'What is AI':
                          case 'what is ai':
                            case 'define ai':
                              case 'define  AI':
                          case 'What is artificial intelligence?':
                          case 'what is artificial intelligence':
                            case 'define artificial intelligence':
                          return 'AI (Artificial Intelligence) refers to intelligence exhibited by machines, particularly computer systems.';
                          case 'Who is the father of AI?':
                          case 'who is the father of ai':
                            case 'which is the father of ai':
                          return 'John McCarthy is considered the father of AI.';
                          case 'What is machine learning?':
                          case 'what is machine learning':
                            case 'define machine learning':
                          return 'Machine learning is a type of AI that enables machines to learn from data and improve their performance on a task without being explicitly programmed.';
                          case 'What is deep learning?':
                          case 'what is deep learning':
                            case 'define deep learning':
                          return 'Deep learning is a type of machine learning that uses neural networks to analyze data.';
                          case 'What is natural language processing?':
                          case 'what is natural language processing':
                            case 'define natural language processing':
                          return 'Natural language processing (NLP) is a subfield of AI that deals with the interaction between computers and humans in natural language.'
                          case 'What is programming?':
  case 'what is programming':
    case 'define programming':
  return 'Programming is the process of designing, writing, testing, and maintaining the source code of computer programs.';
  case 'What is a programming language?':
  case 'what is a programming language':
    case 'define programming language':
  return 'A programming language is a set of rules and instructions that a computer can understand and execute.';
  case 'What is HTML?':
  case 'what is html':
    case 'define html':
  return 'HTML (Hypertext Markup Language) is the standard markup language used to create web pages.';
  case 'What is CSS':
  case 'what is css':
    case 'define css':
  return 'CSS (Cascading Style Sheets) is a styling language used to control the layout and appearance of web pages.';
  case 'What is JavaScript?':
  case 'what is javascript':
    case 'define javascript':
  return 'JavaScript is a high-level, dynamic, and interpreted programming language used for client-side scripting on the web.';
  case 'What is Python?':
  case 'what is python':
    case 'define python':
  return 'Python is a high-level, interpreted programming language used for various purposes such as web development, scientific computing, and data analysis.';
  case 'What is Java?':
    case 'what is java':
      case 'define java':
  return 'Java is an object-oriented programming language used for developing large-scale applications, including Android apps and web applications.';
  case 'What is a variable?':
  case 'define variable':
  return 'A variable is a named storage location that holds a value that can be used in a program.';
  case 'What is a function?':
  case 'define function':
  return 'A function is a block of code that can be called multiple times from different parts of a program.';
  case 'Which is the capital of Pakistan?':
  case 'which is the capital of pakistan':
  return 'Islamabad is the capital of Pakistan.';
  case 'Which is the largest city of Pakistan?':
  case 'which is the largest city of pakistan':
  return 'Karachi is the largest city of Pakistan.';
  case 'What is the national language of Pakistan?':
  case 'what is the national language of pakistan':
  return 'Urdu is the national language of Pakistan.';
  case 'What is the total population of Pakistan?':
  case 'what is the total population of pakistan':
  return 'The population of Pakistan is approximately 235 million people.';
  case 'What is the currency of Pakistan?':
  case 'what is the currency of pakistan':
  return 'The Pakistani rupee (PKR) is the currency of Pakistan.';
  case 'Who is the founder of Pakistan?':
  case 'who is the founder of pakistan':
  return 'Muhammad Ali Jinnah is the founder of Pakistan.';
  case 'Which is the national animal of Pakistan?':
  case 'which is the national animal of pakistan':
  return 'The markhor is the national animal of Pakistan.';
  case 'Which is the highest mountain peak in Pakistan?':
  case 'which is the highest mountain peak in pakistan':
  return 'K2, located in the Karakoram range, is the highest mountain peak in Pakistan.';
  case 'Which is the longest river in Pakistan?':
  case 'which is the longest river in pakistan':
  return 'The Indus River is the longest river in Pakistan, stretching over 3,180 kilometers.';
  case 'Which is the largest province of Pakistan by land area?':
  case 'which is the largest province of pakistan by land area':
  return 'Balochistan is the largest province of Pakistan by land area, covering over 347,190 square kilometers.';
  case 'Which is the most widely spoken language in Pakistan?':
  case 'which is the most widely spoken language in pakistan':
  return 'Punjabi is the most widely spoken language in Pakistan, with over 70 million speakers.';
  case 'Which is the national dish of Pakistan?':
  case 'which is the national dish of pakistan':
  return 'Biryani is the national dish of Pakistan, made with a mixture of spices, basmati rice, and marinated meat or vegetables.';
  case 'Which is the most popular sport in Pakistan?':
  case 'which is the most popular sport in pakistan':
  return 'Cricket is the most popular sport in Pakistan, with a huge following and a successful national team.';
  case 'Which is the oldest city in Pakistan?':
  case 'whih is the oldest city in pakistan':
  return 'Taxila is the oldest city in Pakistan, dating back to the 6th century BCE and a UNESCO World Heritage Site.';
  case 'Which is the highest mountain pass in Pakistan?':
  case 'which is the highest mountain pass in pakistan':
  return 'The Khunjerab Pass is the highest mountain pass in Pakistan, located at an elevation of 4,693 meters.';
  case 'define sentence?':
  case 'what is a sentence?':
  return 'A sentence is a group of words that expresses a complete thought or idea.';
  case 'define declarative sentence':
  case 'what is a declarative sentence':
  return 'A declarative sentence is a sentence that states a fact or opinion.';
  case 'define interrogative sentence':
  case 'what is an interrogative sentence':
  return 'An interrogative sentence is a sentence that asks a question.';
  case 'define imperative sentence':
  case 'what is an imperative sentence':
  return 'An imperative sentence is a sentence that gives a command or makes a request.';
  case 'define compound sentence':
  case 'what is a compound sentence':
  return 'A compound sentence is a sentence that contains two or more independent clauses joined by a conjunction.';
  case 'define complex sentence':
  case 'what is a complex sentence':
  return 'A complex sentence is a sentence that contains an independent clause and one or more dependent clauses.';
  case 'define simple sentence':
  case 'what is a simple sentence':
  return 'A simple sentence is a sentence that contains only one independent clause.';
  case 'define sentence fragment?':
  case 'what is a sentence fragment':
  return 'A sentence fragment is a group of words that does not express a complete thought or idea.';
  case 'What is a run-on sentence?':
  case 'what is a run-on sentence':
  return 'A run-on sentence is a sentence that contains two or more independent clauses that are not joined by a conjunction.';
  case 'define clause':
  case 'what is a clause':
  return 'A clause is a group of words that contains a subject and a predicate.';
  case 'define phrase':
  case 'what is a phrase':
  return 'A phrase is a group of words that does not contain a subject-verb combination.';
  case 'define verb':
  case 'what is a verb':
  return 'A verb is a word that expresses action, occurrence, or state of being.';
  case 'define noun':
  case 'what is a noun':
  return 'A noun is a word that refers to a person, place, thing, or idea.';
  case 'define adjective':
  case 'what is an adjective':
  return 'An adjective is a word that modifies, or describes, a noun or pronoun.';
  case 'define adverb':
  case 'what is an adverb':
  return 'An adverb is a word that modifies, or describes, a verb, an adjective, or another adverb.';
  case 'define pronoun':
  case 'what is a pronoun':
  return 'A pronoun is a word that takes the place of a noun in a sentence.';
  case 'define preposition':
  case 'what is a preposition':
  return 'A preposition is a word that shows the relationship between a noun or pronoun and other words in a sentence.';
  case 'What is a conjunction?':
  case 'what is a conjunction':
    case 'define conjunction':
  return 'A conjunction is a word that joins two words, phrases, or clauses together.';
  case 'define article':
  case 'what is an article':
  return 'An article is a word that modifies a noun and indicates whether it is specific or general.';
  case 'What is the Urdu word for "hello"?':
  case 'what is the urdu word for "hello"':
  return 'The Urdu word for "hello" is "اسلام علیکم" (As-salamu alaykum).';
  case 'What is the English translation of "مجھے آپ سے محبت ہے"?':
  case 'what is the english translation of "مجھے آپ سے محبت ہے"?':
  return 'The English translation of "مجھے آپ سے محبت ہے" is "I love you".';
  case 'What is the Urdu word for "water"?':
  case 'what is the urdu word for "water"?':
  return 'The Urdu word for "water" is "پانی" (pāni).';
  case 'What is the English translation of "میں آپ کا شکر گزار ہوں"?':
  case 'what is the english translation of "میں آپ کا شکر گزار ہوں"?':
  return 'The English translation of "میں آپ کا شکر گزار ہوں" is "I am grateful to you".';
  case 'What is the Urdu word for "thank you"?':
  case 'what is the urdu word for "thank you"?':
  return 'The Urdu word for "thank you" is "شکریہ" (shukriya).';
  case 'What is the English translation of "آپ کیسے ہو؟"?':
  case 'what is the english translation of "آپ کیسے ہو؟"?':
  return 'The English translation of "آپ کیسے ہو؟" is "How are you?".'
  case 'What is the fundamental force of nature that causes objects to attract each other?':
  case 'what is the fundamental force of nature that causes objects to attract each other?':
  return 'Gravity.'
  case 'What is the fastest speed at which an object can travel?':
  case 'what is the fastest speed at which an object can travel':
  return 'The speed of light (approximately 186,282 miles per second).'
  case 'What is the process by which water moves through a plant from the roots to the leaves and is then released into the air as water vapor?':
  case 'what is the process by which water moves through a plant from the roots to the leaves and is then released into the air as water vapor':
  return 'Transpiration.'
  case 'What is the scientific concept that describes the relationship between energy and matter?':
  case 'what is the scientific concept that describes the relationship between energy and matter':
  return 'E=mc^2 (mass-energy equivalence).'
  case 'What is the scientific principle that states that energy cannot be created or destroyed only converted from one form to another?':
  case 'what is the scientific principle that states that energy cannot be created or destroyed only converted from one form to another':
  return 'The Law of Conservation of Energy.'
  case 'What is the scientific theory that describes the behavior of very small objects such as atoms and subatomic particles?':
  case 'what is the scientific theory that describes the behavior of very small objects such as atoms and subatomic particles':
  return 'Quantum Mechanics.'
  case 'What is the SI unit of force?':
  case 'what is the si unit of force':
  return 'Newton (N).'
  
  case 'What is the process by which a solid changes directly into a gas?':
  case 'what is the process by which a solid changes directly into a gas':
  return 'Sublimation.'
  case 'What is the scientific term for the "building blocks of life"?':
  case 'what is the scientific term for the building blocks of life':
  return 'Cells.'
  case 'What is the process by which plants make their own food from sunlight?':
  case 'what is the process by which plants make their own food from sunlight':
  return 'Photosynthesis.'
  case 'What is the scientific concept that describes the relationship between distance, speed, and time?':
  case 'what is the scientific concept that describes the relationship between distance speed and time':
  return 'Speed = Distance / Time.'
  case 'What is the scientific term for the study of the structure, behavior, and evolution of the universe?':
  case 'what is the scientific term for the study of the structure behavior and evolution of the universe':
  return 'Cosmology.'
  case 'What is the process by which a liquid changes into a gas?':
  case 'what is the process by which a liquid changes into a gas':
  return 'Vaporization.'
  case 'What is the scientific principle that states that energy cannot be created or destroyed, only converted from one form to another?':
  case 'what is the scientific principle that states that energy cannot be created or destroyed only converted from one form to another':
  return 'The Law of Conservation of Energy.'
  case 'What is the scientific term for the "smallest unit of life"?':
  case 'what is the scientific term for the smallest unit of life':
  return 'Cell.'
  case 'What is the process by which plants release water vapor into the air?':
  case 'what is the process by which plants release water vapor into the air':
  return 'Transpiration.'
  case 'What is the scientific concept that describes the relationship between force, mass, and acceleration?':
  case 'what is the scientific concept that describes the relationship between force mass and acceleration':
  return 'F = ma (Force = mass x acceleration).'
  case 'What is the scientific term for the study of the structure, properties, and reactions of matter?':
  case 'what is the scientific term for the study of the structure properties and reactions of matter':
  return 'Chemistry.'
  
  case 'What is the scientific principle that states that every point on a wave has the same frequency and wavelength':
  case 'what is the scientific principle that states that every point on a wave has the same frequency and wavelength':
  return 'Wave theory.'
  case 'What is the scientific term for the "smallest unit of matter"?':
  case 'what is the scientific term for the smallest unit of matter':
  return 'Atom.'
  case 'What is the process by which a gas changes into a liquid?':
  case 'what is the process by which a gas changes into a liquid':
  return 'Condensation.'
  
  case 'What is the scientific term for the study of the behavior, physiology, and evolution of living organisms?':
  case 'what is the scientific term for the study of the behavior physiology and evolution of living organisms':
  return 'Biology.'
  case 'What is the scientific term for the force that opposes motion between two surfaces in contact?':
  case 'what is the scientific term for the force that opposes motion between two surfaces in contact':
  return 'Friction.'
  case 'What is the process by which a solid changes into a liquid?':
  case 'what is the process by which a solid changes into a liquid':
  return 'Melting.'
  
  case 'What is the scientific term for the "building blocks of matter"?':
  case 'what is the scientific term for the building blocks of matter':
  return 'Atoms.'
  case 'What is the process by which plants make their own food from sunlight, water, and carbon dioxide?':
  case 'what is the process by which plants make their own food from sunlight water and carbon dioxide':
  return 'Photosynthesis.'
  case 'What is the scientific concept that describes the relationship between the frequency and wavelength of a wave?':
  case 'what is the scientific concept that describes the relationship between the frequency and wavelength of a wave':
  return 'Wave theory (f = c / λ).'
  case 'What is the scientific term for the study of the structure properties and reactions of matter':
  case 'what is the scientific term for the study of the structure properties and reactions of matter':
  return 'Chemistry.'
  case 'What is the process by which a liquid changes into a solid':
  case 'what is the process by which a liquid changes into a solid':
  return 'Freezing.'
  
  case 'What is the speed of light in vacuum?':
  case 'what is the speed of light in vacuum':
  return 'Approximately 299,792,458 meters per second (m/s).'
  case 'What is the largest planet in our solar system?':
  case 'what is the largest planet in our solar system':
  return 'Jupiter.'
  case 'What is the process by which water moves through a plant, from the roots to the leaves, and is then released into the air as water vapor?':
  case 'what is the process by which water moves through a plant from the roots to the leaves and is then released into the air as water vapor':
  return 'Transpiration.'
  
  case 'What is the smallest unit of matter?':
  case 'what is the smallest unit of matter':
  return 'Atom.'
  
  
  case 'What is the largest living structure on Earth?':
  case 'what is the largest living structure on earth':
  return 'The Great Barrier Reef.'
  case 'What is the scientific term for the "building blocks of life"?':
  case 'what is the scientific term for the building blocks of life':
  return 'Cells.'
  case 'What is the process by which plants make their own food from sunlight, water, and carbon dioxide?':
  case 'what is the process by which plants make their own food from sunlight water and carbon dioxide':
  return 'Photosynthesis.'
  case 'What is your name?':
  case 'what is your name':
  return 'I do not have any name because, I am AI.'
  case 'define physics':
  case 'what is physics':
  return 'Physics is the scientific study of the natural world around us. It involves the study of matter, energy, and the fundamental laws that govern the behavior of the physical universe. Physics is a branch of science that seeks to understand the natural phenomena that occur in the universe, from the smallest subatomic particles to the entire cosmos.';
  case 'define chemistry':
  case 'what is chemistry':
  return 'Chemistry is the scientific study of the composition, properties, and reactions of matter. It is a branch of science that deals with the study of the building blocks of matter, including atoms, molecules, and ions, and how they interact with each other to form new substances.';
  case 'define biology':
  case 'what is biology':
  return 'Biology is the scientific study of life and living organisms. It is a branch of science that deals with the study of the structure, function, growth, evolution, distribution, and taxonomy of all living things, from the simplest bacteria to complex ecosystems.';
  case 'define computer':
  case 'what is computer':
  return 'A computer is an electronic device that can store, process, and communicate information. It is a machine that can be programmed to perform a wide range of tasks, from simple calculations to complex simulations, and can be used for a variety of purposes, including communication, education, and entertainment.';
  case 'define english':
  case 'what is english':
  return 'English is a West Germanic language that originated from Anglo-Frisian dialects brought to Britain in the mid-5th to 7th centuries AD. It is a global language, widely used for international communication in business, science, technology, and entertainment, and is the primary language used for international communication in many countries.';
  case 'define car':
  case 'what is car':
  return 'A car, also known as an automobile, is a wheeled motor vehicle that is designed to transport people and cargo. It is typically powered by an internal combustion engine or electric motor, and has a body, chassis, and wheels.';
  case 'define engine':
  case 'what is engine':
  return 'An engine is a machine that converts energy into mechanical motion or power. In a car, the engine is the component that generates power, typically using fuel such as gasoline or diesel, and transmits it to the wheels.';
  case 'define transmission':
  case 'what is transmission':
  return 'A transmission is a system that transmits power from the engine to the wheels of a car, allowing the vehicle to move at different speeds. It uses gears and other components to adjust the speed and torque of the power being transmitted.';
  case 'define brake':
  case 'what is brake':
  return 'A brake is a system that slows or stops a car by applying friction to the wheels. It typically consists of a pedal, master cylinder, and brake pads or shoes that press against the wheels to slow or stop the vehicle.';
  
  case 'write a short essay on the importance of time management':
  case 'why is time management important':
  return 'Effective time management is crucial for achieving goals and reducing stress. It enables individuals to prioritize tasks, allocate sufficient time for each activity, and avoid procrastination. By managing time wisely, individuals can increase productivity, improve work-life balance, and enhance overall well-being. In todays fast-paced world, time management is essential for success in both personal and professional spheres.';
  case 'discuss the impact of social media on mental health':
  case 'how does social media affect mental health':
  return 'Social media has a profound impact on mental health, with both positive and negative effects. On the one hand, social media provides a platform for connection, self-expression, and community building. On the other hand, excessive social media use can lead to comparison, anxiety, depression, and loneliness. Cyberbullying, online harassment, and the pressure to present a perfect online persona can further exacerbate mental health concerns. It is essential to use social media responsibly and mindfully to promote healthy online interactions and digital well-being.';
  case 'explain the concept of climate change':
  case 'what is climate change':
  return 'Climate change refers to the long-term warming of the planet due to an increase in average global temperature. This phenomenon is primarily caused by human activities such as burning fossil fuels, deforestation, and pollution, which release large amounts of greenhouse gases into the atmosphere. Climate change has severe consequences, including rising sea levels, extreme weather events, and disruptions to ecosystems and biodiversity. Urgent action is necessary to mitigate the effects of climate change and ensure a sustainable future for our planet.';
  case 'describe the benefits of reading':
  case 'why is reading important':
  return 'Reading is a vital activity that offers numerous benefits for individuals of all ages. It enhances language skills, improves vocabulary, and boosts critical thinking and analytical abilities. Reading exposes individuals to new ideas, perspectives, and cultures, fostering empathy and broadening horizons. It also provides a relaxing and enjoyable escape from the stresses of everyday life, improving mental health and well-being. Moreover, reading is essential for academic and professional success, as it expands knowledge and understanding of the world around us.'
  case 'write a short essay on the importance of teamwork':
  case 'why is teamwork important':
  return 'Teamwork is the cornerstone of success in any endeavor. When individuals work together towards a common goal, they bring unique skills, perspectives, and experiences to the table. This collaboration fosters creativity, innovation, and problem-solving, leading to better outcomes and increased productivity. Teamwork also promotes accountability, trust, and communication among team members, building strong relationships and a sense of camaraderie. In today fast-paced and interconnected world, teamwork is essential for achieving complex goals and driving progress.';
  case 'discuss the impact of technology on communication':
  case 'how has technology changed communication':
  return 'Technology has revolutionized communication, transforming the way we connect, interact, and share information. The advent of social media, messaging apps, and video conferencing has made communication faster, more convenient, and accessible. However, technology has also led to the decline of face-to-face communication, deepened the digital divide, and raised concerns about privacy and misinformation. As technology continues to evolve, it is crucial to harness its potential while maintaining empathy, understanding, and responsible communication practices.'
  case 'explain the concept of emotional intelligence':
  case 'what is emotional intelligence':
  return 'Emotional intelligence (EI) refers to the ability to recognize and understand emotions in oneself and others, and to use this awareness to guide thought and behavior. EI encompasses self-awareness, self-regulation, motivation, empathy, and social skills. It enables individuals to navigate complex social situations, build strong relationships, and make informed decisions. Developing emotional intelligence is essential for personal growth, effective leadership, and success in both personal and professional spheres.'
  case 'describe the benefits of learning a foreign language':
  case 'why learn a foreign language':
  return 'Learning a foreign language offers a wealth of benefits, including improved cognitive skills, enhanced cultural understanding, and increased career opportunities. It allows individuals to communicate with diverse communities, appreciate literature and art in their original form, and explore new perspectives. Language learning also boosts memory, problem-solving abilities, and multi-tasking skills, while delaying age-related cognitive decline. In an increasingly globalized world, speaking multiple languages is a valuable asset for personal and professional growth.'
  case 'What is Islam':
  case 'what is islam':
  case 'define islam':
  case 'define Islam':
  case 'What is the meaning of Islam':
  case 'what is the meaning of islam':
    return 'Islam (الإسلام) means submission to the will of Allah (God) and obedience to His commands.';
  
  case 'Who is Muhammad':
  case 'who is muhammad':
  case 'define muhammad':
  case 'define Muhammad':
  case 'What is the significance of Muhammad':
  case 'what is the significance of muhammad':
    return 'Muhammad (محمد) is the final prophet sent by Allah to guide humanity, considered the embodiment of the Quran\'s teachings.';
  
  case 'What is the Quran':
  case 'what is the quran':
    case 'what is quran':
  case 'define quran':
  case 'define Quran':
  case 'What is the significance of the Quran':
  case 'what is the significance of the quran':
    return 'The Quran (القرآن) is the holy book of Islam, revealed to Prophet Muhammad, considered the word of Allah as revealed to humanity.';
  
  case 'What is the Kaaba':
  case 'what is the kaaba':
    case 'what is kaaba':
  case 'define kaaba':
  case 'define Kaaba':
  case 'What is the significance of the Kaaba':
  case 'what is the significance of the kaaba':
    return 'The Kaaba (الكعبة) is a cube-shaped building in Makkah, considered the holiest site in Islam, and the direction of prayer for Muslims worldwide.';
  
  case 'What is Ramadan':
  case 'what is ramadan':
  case 'define ramadan':
  case 'define Ramadan':
  case 'What is the significance of Ramadan':
  case 'what is the significance of ramadan':
    return 'Ramadan (رمضان) is the ninth month of the Islamic calendar, a time of fasting, reflection, and spiritual growth for Muslims worldwide.';
    case 'What is Hadith':
  case 'what is hadith':
  case 'define hadith':
  case 'define Hadith':
  case 'What is the significance of Hadith':
  case 'what is the significance of hadith':
    return 'Hadith (الحديث) refers to the sayings, actions, and approvals of Prophet Muhammad, considered a source of guidance for Muslims.';
  
  case 'What is Sunnah':
  case 'what is sunnah':
  case 'define sunnah':
  case 'define Sunnah':
  case 'What is the significance of Sunnah':
  case 'what is the significance of sunnah':
    return 'Sunnah (السنة) refers to the way of life and teachings of Prophet Muhammad, considered a model for Muslims to follow.';
  
  case 'What is Sharia':
  case 'what is sharia':
  case 'define sharia':
  case 'define Sharia':
  case 'What is the significance of Sharia':
  case 'what is the significance of sharia':
    return 'Sharia (الشريعة) refers to Islamic law, derived from the Quran and Hadith, guiding Muslims in their daily lives and moral conduct.';
  
  case 'What is Zakat':
  case 'what is zakat':
    case 'tell ma about zakat':
  case 'define zakat':
  case 'define Zakat':
  case 'What is the significance of Zakat':
  case 'what is the significance of zakat':
    return 'Zakat (زكاة) is the practice of giving a portion of one\'s wealth to the poor and needy, considered a fundamental aspect of Islamic faith.';
    case 'tell me about hajj':
  case 'What is Hajj':
  case 'what is hajj':
  case 'define hajj':
  case 'define Hajj':
  case 'What is the significance of Hajj':
  case 'what is the significance of hajj':
    return 'Hajj (حج) is  the annual pilgrimage to Makkah, considered a once-in-a-lifetime obligation for Muslims, symbolizing unity and spiritual renewal.';
    case 'What is the name of the Prophet':
  case 'what is the name of the prophet':
  case 'Who is the Prophet':
  case 'who is the prophet':
    return 'The Prophet\'s name is Muhammad (محمد), meaning "praiseworthy"';
  
  case 'What is the Prophet\'s title':
  case 'what is the prophet\'s title':
    return 'The Prophet Muhammad is often referred to as "Rasul Allah" (رسول الله), meaning "Messenger of God"';
  
  case 'What is the Prophet\'s role':
  case 'what is the prophet\'s role':
    return 'The Prophet Muhammad is considered the final messenger sent by Allah to guide humanity, and his role is to convey the message of Islam';
  
  case 'What are the Prophet\'s attributes':
  case 'what are the prophet attributes':
    return 'The Prophet Muhammad is known for his honesty, trustworthiness, mercy, compassion, and wisdom, among other noble qualities';
  case "prophet birthday":
  case 'What is the significance of the Prophet\'s birthday':
  case 'what is the significance of the prophet\'s birthday':
    return 'The Prophet Muhammad\'s birthday, known as "Mawlid al-Nabi" (مولد النبي), is celebrated by Muslims around the world to commemorate his birth and legacy';
    case 'Who is Abu Jahl':
  case 'who is abu jahl':
    return 'Abu Jahl (أبو جهل) was a prominent leader of the Quraysh tribe and a fierce opponent of the Prophet Muhammad and Islam';
  
  case 'Who is Abu Lahab':
  case 'who is abu lahab':
    return 'Abu Lahab (أبو لهب) was a uncle of the Prophet Muhammad and a strong opponent of Islam, known for his cruelty and persecution of Muslims';
  
  case 'What is the meaning of Munafiq':
  case 'what is the meaning of munafiq':
    return 'Munafiq (منافق) refers to a hypocrite, someone who claims to be a Muslim but secretly opposes Islam and works against the Muslim community';
  
  case 'Who are the Ahl al-Kitab':
  case 'who are the ahl al-kitab':
    return 'Ahl al-Kitab (أهل الكتاب) refers to the People of the Book, specifically Jews and Christians, who received revelations from Allah but rejected the prophethood of Muhammad';
  
  case 'What is the meaning of Kafir':
  case 'what is the meaning of kafir':
    return 'Kafir (كافر) refers to a disbeliever, someone who rejects the existence of Allah or the prophethood of Muhammad, and refuses to submit to the will of Allah';
    case 'Who is Iblees':
  case 'who is iblees':
    return 'Iblees (إبليس) is the Islamic name for Satan, the devil who refused to bow down to Adam and was cast out of heaven';
  
  case 'What is the meaning of Dajjal':
  case 'what is the meaning of dajjal':
    return 'Dajjal (دجال) refers to the Islamic equivalent of the Antichrist, a powerful and deceitful figure who will appear before the end of time';
  
  case 'Who is Firawn':
  case 'who is firawn':
    return 'Firawn (فرعون) was the Pharaoh of Egypt who oppressed the Israelites and rejected the prophethood of Moses';
  
  case 'Who are the Munafiqeen':
  case 'who are the munafiqeen':
    return 'Munafiqeen (منافقون) refers to a group of hypocrites who claimed to be Muslims but secretly opposed the Prophet Muhammad and Islam';
  
  case 'What is the meaning of Taghut':
  case 'what is the meaning of taghut':
    return 'Taghut (تاغوت) refers to anything that is worshipped or obeyed instead of Allah, including false gods, idols, and oppressive rulers';
    case 'Who is Imran Khan':
  case 'who is imran khan':
    return 'Imran Khan (عمران خان) is a Pakistani politician and former cricketer who served as the 22nd Prime Minister of Pakistan from 2018 to 2022';
  
  case 'What is Imran Khan\'s political party':
  case 'what is imran khan political party':
   return 'Imran Khan is the chairman of the Pakistan Tehreek-e-Insaf (PTI) party';
  
  case 'What is Imran Khan\'s cricket background':
  case 'what is imran khan cricket background':
    return 'Imran Khan was a successful cricketer who played for the Pakistan national team from 1971 to 1992 and was captain of the team that won the 1992 Cricket World Cup';
  
  case 'What are Imran Khan\'s notable achievements':
  case 'what are imran khan notable achievements':
    return 'Imran Khan\'s notable achievements include leading the Pakistan cricket team to World Cup victory, founding the PTI party, and becoming the Prime Minister of Pakistan';
  
  case 'What is Imran Khan\'s vision for Pakistan':
  case 'what is imran khan vision for pakistan':
    return 'Imran Khan\'s vision for Pakistan includes creating a corruption-free and just society, promoting economic growth and development, and strengthening the country\'s international relations';
    case 'What is Imran Khan stance on corruption':
      case 'what is imran khan\'s stance on corruption':
        return 'Imran Khan has been a vocal critic of corruption and has promised to eradicate it from Pakistan';
      
      case 'What is Imran Khan economic policy':
      case 'what is imran khan economic policy':
        return 'Imran Khan economic policy focuses on promoting economic growth, reducing poverty and inequality, and increasing foreign investment in Pakistan';
      
      case 'What is Imran Khan foreign policy':
      case 'what is imran khan foreign policy':
        return 'Imran Khan foreign policy prioritizes strengthening relations with neighboring countries, promoting regional peace and stability, and resolving conflicts through diplomacy';
      
      case 'What is Imran Khan stance on terrorism':
      case 'what is imran khan stance on terrorism':
        return 'Imran Khan has been a strong critic of terrorism and has promised to combat it effectively, including through military action and diplomatic efforts';
      
      case 'What is Imran Khans vision for education in Pakistan':
      case 'what is imran khan vision for education in pakistan':
        return "Imran Khan vision for education in Pakistan includes increasing access to quality education promoting literacy and reforming the education system to meet modern challenges";
    case "who is ahmad nawaz":
      case"tell me about ahmad nawaz":
      return"Ahmad Nawaz is the very bad friend of Ayyan.He always Abuse him,and he have an degree called in hindi SHOKHI DEGREE By gainning 100% marks"
  case"who is umer iqbal":
  case"who is umer iqbal qadri":
  return"Umer Iqbal is the friend of Ayyan and I cannot provide information about Umer Iqbal."
  case"who is zubair afzal":
  case"who is zubair afzal":
  return"Zubair Afzal is the friend of Ayyan and I cannot provide information about Zubair Afzal." 
  
  
  default:
        return 'I didn\'t understand that. Please try again!.';
    }
  }
   
  function displayResponse(response) {
    const responseHTML = `<p>${response}</p>`;
    responseContainer.innerHTML = responseHTML;
  }
  
  function saveChat(userQuestion, response) {
    const chatHTML = `<p>You: ${userQuestion}</p><p>AI: ${response}</p>`;
    chatLog.innerHTML += chatHTML;
  }
